'Module Classe: clsStyle
Public Index as Integer
Public SheetName as String
Public gender as String
Public GenderASCII as String
Public tagsGenre as String
public tagsCollections as String
public googlegender as String
public prix as Currency
public VPN123 as Integer
public Style as String
public style_camel_case as String
public couleurdebut as Byte
public couleurfin as Byte
public couleursoriginales as Variant
public googleage as String
public a as Byte
public b as Byte
public seo as String