'Module Classe: clsVariant
Public Handle as String
Public Title as String
Public Body_HTML as String
Public Vendor as String
Public Tags as String
Public Published as String
Public Option1_Name as String
Public Option1_Value as String
Public Option2_Name as String
Public Option2_Value as String
Public Variant_SKU as String
Public Variant_Inventory_Tracker as String
Public Variant_Inventory_Qty as Integer
Public Variant_Inventory_Policy as String
Public Variant_Fulfillment_Service as String
Public Variant_Requires_Shipping as String
Public Variant_Taxable as String
Public Image_Src as String